# Generated by Django 4.2 on 2023-06-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_tracker', '0003_device_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelog',
            name='checkout_condition',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='checkout_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='return_condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
